### ISSUE TITLE
Type EPaymentGetPaymentOKResponse missing property metadata

### ISSUE THREAD

**Issue by melanki** [vippsas/deno-sdk#19]
According to Vipps ePayment API specs the object GetPaymentResponse should have the property metadata.
During migration from vipps-sdk we discovered that this property is no longer available in this new SDK.

Could this be corrected? As we are using this to add metadata required by our eCommerce solution.

**Comment by tomas-zijdemans-vipps** [comment]
Thanks so much for reporting @melanki. I have done an initial investigation and can confirm that you are correct. The current epayment types lack metadata (and also receipt - so I will do a QA of all the ePayment types).

Please note that these types are copied from the old SDK, so this has been a bug all along (for both the old and new SDK).

I'll release a fix as soon as possible. Please feel free to send in any other issues, questions or just general feedback on the SDK! 👍

**Comment by tomas-zijdemans-vipps** [comment]
This should fix the issue: https://github.com/vippsas/deno-sdk/pull/22. Please verify once this has been merged :)

**Comment by tomas-zijdemans-vipps** [comment]
Fixed in [0.6.0](https://github.com/vippsas/deno-sdk/releases/tag/0.6.0 )

Please let us know if you have further issues, questions or feedback :)
