### ISSUE TITLE
EPaymentPaymentEventOKResponse should not be an array

### ISSUE THREAD

**Issue by melanki** [vippsas/deno-sdk#23]
**Describe the bug**

EPaymentPaymentEventOKResponse is wrongfully typed as an array of events.

If it is only intended for Payment Event History Response as commented in code, SDK should define a PaymentEvent object and EPaymentPaymentEventOKResponse should have an array of this object.

TL:DR; Missing [PaymentEvent object](https://github.com/vippsas/node-sdk/blob/2a9e10bb8caee08cb400c175d78f26873b338f6f/src/%40types/epayment.types.ts#L387)

**Expected behavior**

Based on this documentation: https://developer.vippsmobilepay.com/docs/APIs/epayment-api/features/webhooks/

As a developer I expect to receive an object representing an event on my endpoint.
EPaymentPaymentEventOkResponse is wrongfully typed or SDK is missing an object for webhook events.

**Comment by tomas-zijdemans-vipps** [comment]
I will look into the Webhook event shortly

**Comment by tomas-zijdemans-vipps** [comment]
@melanki : I updated the PR to add the missing Webhook type (for both ePayment and Qr). Will release a new version once it has been approved.

**Comment by tomas-zijdemans-vipps** [comment]
Fixed in 0.7.0

**Comment by melanki** [comment]
Thank you for the quick response, will verify it later today.
