### ISSUE TITLE
ReferenceError: crypto is not defined

### ISSUE THREAD

**Issue by viktorfa** [vippsas/deno-sdk#49]
I got `ReferenceError: crypto is not defined` when using the client on Node 18 in AWS Lambda.

It can be fixed in your code with the line `global.crypto = require("node:crypto");`

**Comment by flinkgutt** [comment]
Thank you for reporting this! :)

**Comment by tomas-zijdemans-vipps** [comment]
@viktorfa This should now be fixed. Please Reopen the issue if you still have an issue :)

**Comment by seiji-genies** [comment]
Thank you! @viktorfa
