### ISSUE TITLE
Can't build in Node-based project in 1.3.4

### ISSUE THREAD

**Issue by Jaggler3** [vippsas/deno-sdk#55]
**Describe the bug**
When building a project with @vippsmobilepay/sdk as a dependency, it fails with this error:
```
./node_modules/@vippsmobilepay/sdk/esm/errors.js
Module not found: Can't resolve '@std/async'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/@vippsmobilepay/sdk/esm/base_client.js
./node_modules/@vippsmobilepay/sdk/esm/mod.js
```

I downgraded from 1.3.4 to 1.3.1 and was able to build without issue.

**To Reproduce** 

1. Create a NextJS project
2. Install @vippsmobilepay/sdk
3. Run `yarn build`
4. Observe failing build
5. Reinstall downgraded version with `yarn add @vippsmobilepay/sdk@1.3.1`
6. Observe successful build

**Expected behavior** 
The build should not fail

**Desktop (please complete the following information):**

- OS: Arch Linux, also fails in Vercel
- Browser: N/A
- Version N/A

**Additional context**
I see recent commits regarding dependency management updates, but not sure if it is relevant.

**Comment by tomas-zijdemans-vipps** [comment]
Thank you for reporting, I'll look into this!

**Comment by sommeeeer** [comment]
Can confirm this happened to me aswell on version `1.3.4` with `pnpm` as package manager. 

All the modules starting with '@std/*' . These are packages that are located in JSR [(@std).](https://jsr.io/@std) To make it work in NodeJS environment you have to install them by doing `pnpm dlx jsr add @std/package-name`.

A quick fix to get all the dependencies for `1.3.4` is to run `pnpm dlx jsr add @std/async @c4spar/mock-fetch @deno/dnt @std/assert @std/cli @std/collections @std/fmt @std/http @std/media-types @std/semver`.

However, this will probably still not work cause this package is dependent on Deno, and therefore will throw some errors saying `Deno is not defined`.

**Comment by sommeeeer** [comment]
Can confirm this happened to me aswell on version `1.3.4` with `pnpm` as package manager. 

All the modules starting with `@std/*` . These are packages that are located in JSR [(@std).](https://jsr.io/@std) To make it work in NodeJS environments you have to install them by doing `pnpm dlx jsr add @std/package-name`.

A quick way to get all the dependencies for `1.3.4` is to run `pnpm dlx jsr add @std/async @c4spar/mock-fetch @deno/dnt @std/assert @std/cli @std/collections @std/fmt @std/http @std/media-types @std/semver`.

However, this will probably still not work cause this package is dependent on Deno, and therefore will throw some errors saying `Deno is not defined`.

**Comment by tomas-zijdemans-vipps** [comment]
Thanks for the input @sommeeeer. DNT is used to build the node package, so there might be some funny business going on there.

**Comment by tomas-zijdemans-vipps** [comment]
@Jaggler3 : I've followed your steps to reproduce with version 2.0.0 and everything seems to work, please report back if you have any issues or questions :)
