### ISSUE TITLE
Checkout API gone from v2?

### ISSUE THREAD

**Issue by HP** [vippsas/deno-sdk#59]
> Removed all unused APIs (based on internal monitoring) for now, they were starting to get outdated. Please open an Issue (or send a PR) if you wish to use an API that is not supported in the future.

We are currently building a store to be launched in october, using the checkout API. As described here: https://developer.vippsmobilepay.com/docs/APIs/checkout-api/checkout-api-guide/

When updating from 1.3.4 to 2.0.0 `client.checkout.create()` doesn't work. Is there another way to get the checkout session for the frontend JS using the SDK? I could always do a fetch call to the api, but it was nice to have it in the SDK.

**Comment by tomas-zijdemans-vipps** [comment]
Thanks for reporting this. I'll add Checkout back shortly!

**Comment by tomas-zijdemans-vipps** [comment]
Checkout has been added in 2.1.0 🎉 

Please let me know if you discover any issues, or have any further questions!
