### ISSUE TITLE
Expose /script/types.d.ts

### ISSUE THREAD

**Issue by shinysticker** [vippsas/deno-sdk#61]
**Is your feature request related to a problem? Please describe.**
Hey, I'd like to be able to customise errors in ClientResponses, but the "SDKError" type is not resolvable by any other module format than "node".

**Describe the solution you'd like** 
Would you consider exposing /script/types.d.ts

**Describe alternatives you've considered** 
Currently I'm able to reach the type with a path alias.

Thank You!

**Comment by tomas-zijdemans-vipps** [comment]
Thanks for reporting @shinysticker , I'll have a look shortly

**Comment by tomas-zijdemans-vipps** [comment]
@shinysticker: I'm now exposing the SDKError type as requested (and also ClientConfig, since that's something you might want to type specifically). Let me know if this works for you :)

https://github.com/vippsas/deno-sdk/releases/tag/2.2.0
